package game.scenes;

/**
 * Level 4: Snow
 */
public class Level4 extends GameScene {

  public Level4() {
    super("snow-bg", 4, 0.75);
  }

  @Override
  protected String[] getLevelLayout() {
    return new String[] {
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                  T  T                  ",
        "                                       w                                                                                                             w                                                  ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                  T  T                  ",
        "                                                                                                r     r     r                                                                                           ",
        "                                                                                                                                                                                                        ",
        "                                                                                                  r      r                                                                                              ",
        "                                                                                                                                                                                                        ",
        "                                                                                                r     r      r           *                                                                              ",
        "                                                                                                                                                                                                        ",
        "               w                                                     w                                                                                                                                  ",
        "                                                                                                                                                          T T                                           ",
        "                                                                                                                                                                                              w         ",
        "                                                                                                                                                          T T                                           ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "             0          T         0                                                                                                                                                                     ",
        "                                                                                                                       |              |                                                                 ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "             0          #         0                                                                                                                                           0                         ",
        "                                                                                                                                                                                                        ",
        "                                                                 *                                                                                                                                      ",
        "                                                                                              w                        |              |                 t                                               ",
        "             0          T         0                                                                                                                                                                     ",
        "                                                                                                                                                                              0                         ",
        "             T                    T                                                                                                                                                                     ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                      #                                                                                                                                 ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                             A          ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                     #                                                  ",
        "                                                                                                                                                                                                        ",
        "                                   w                                                                                                                                                                    ",
        "                                                                                                                        w                                                                               ",
        "                                                                                                                                                                                                        ",
        "                                                                                     -                                                                                                                  ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                      *                                                                                                                  w                              ",
        "                                                                                                                                                                                                        ",
        "                                                                                     w                                                                                                                  ",
        "           w                                                                                                                          w                                                                 ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                       R    R   R                                                                                                       ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                         |                              ",
        "                              T  T                                                    R    #    R                                    |                                                                  ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                              T  T                                                                                                                                                                      ",
        "                                                                                                                                                                                                        ",
        "                                                                                      R    R    R                                                                                                       ",
        "                                                                                                                                                                                                        ",
        "                                                             w                                                                       |                                                                  ",
        "                                                                                                                                                                   t                                    ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                    s                                                                                                   ",
        "                                                                                                                                                                                             T T        ",
        "                                                                                                                                                                                                        ",
        "                                      *                                                                                            r  r  r  r  r  r                                          T T        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                      T T T                                                                                                             ",
        "                                                                                                                                                                                                        ",
        "                                                                                      T T T                                                              w                                              ",
        "          T T                                                                                                                                                                                           ",
        "                                                                                                                                                                                                        ",
        "          T T                                                                                                                                                                                           ",
        "                                                                                                                                                                                                        ",
        "                                                                    w                                                                                                                                   ",
        "                                                                                                                                                                   T T                                  ",
        "                     t                                                                                                                                                                                  ",
        "                                                                                                                                                                   T T                                  ",
        "                                              0                 0                                                                                                                                       ",
        "                                                                                                                          w                                                                             ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                  T  T                                                                                                  ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                  T  T                                                                                                  ",
        "                                            -          -                                                                                                              w                                 ",
        "                   0                                                                                                                                                                                    ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                      r  r  r  r  r                                                                     ",
        "                                                                                                                                                                                                        ",
        "                                                                                    w                                                                                                                   ",
        "                                       0                                                                                                                                                                ",
        "                                                                                                                                                                                                        ",
        "                        *                                                                                                                                                                               ",
        "                                                                                                                                         a                                                              ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                             t                                                                                                          ",
        "                                                                                                                                                                                                        ",
        "                                                            T T                                                                                                                             t           ",
        "                                                                                                                                                                                                        ",
        "                                                            T T                                                                                                                                         ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                  T T                                   ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                  T T                                   ",
        "                A                          w                                                                    r  r  r  r  r                                                                           ",
        "                                                                                                                                                                                                        ",
        "                                                                           #                                                                                                                            ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                        w                                                               ",
        "                                                                                                                                                                                                        ",
        "                                                                                                       *                                        R   R                                                   ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                         r                                                                                                                  T T T       ",
        "           t                                                                                                                                    R   R                                                   ",
        "                                                                                                                                                                                                        ",
        "                                             T T                                                                                                                 #                          T T T       ",
        "                                                                                                                                                                                                        ",
        "                                             T T                                                                                                R   R                                                   ",
        "                                                                                                                T T                                                                         T T T       ",
        "                                                                                                                                                                                                        ",
        "                                                                                     w                          T T                                                                                     ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "          r                                                                                                                          *                                                                  ",
        "                                                                                                                                                                                                        ",
        "                              w                                                                                                                                                                         ",
        "                                                              r  r  r  r  r  r                                                                                                                          ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                       w                                ",
        "                                                                                                                                                                                                        ",
    };
  }
}
