package game.scenes;

/**
 * Level 6: Circuit
 */
public class Level6 extends GameScene {

  public Level6() {
    super("circuit-bg", 6);
  }

  @Override
  protected String[] getLevelLayout() {
    return new String[] {
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                      T T                                                    T                                          ",
        "                                                                                                                                                                                                        ",
        "                                                                                                      T T                                                                                               ",
        "         T                                                                                                                                                                                              ",
        "                                                                                                                              0                                                                         ",
        "                                                   0                                                                                                                                                    ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                            A      a      |                                                                                                             ",
        "                                                                                                                                               T T T                                                    ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                               T T T                                                    ",
        "                           T T                                                                                                                                                 T                        ",
        "                                                                                                                                               T T T                                                    ",
        "                           T T                                              A      #      |                        0                                                                                    ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                T                                                                                                                                                       ",
        "                                                                            |      -      A                                                                                                    0        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                               T T                                      ",
        "            0                                                                                                                                                                                           ",
        "                                                                                                                                      0                        T T                                      ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                               T T                                      ",
        "                                    r  r  r  r  r  r                                                                                                                                                    ",
        "                            r  r  r  r  r  r  r  r  r  r  r                                                                                                                                             ",
        "                              r  r  r  r  r  r  r  r  r  r  r                           0                     T T                                                                                       ",
        "                                                                                                                                                                                                        ",
        "                                                                                                              T T                                                                                       ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                     r                                                                                                                                  ",
        "                                                                                                                                                                                                        ",
        "                                  T T                                                                                                                                        |                          ",
        "                                                                                                                                                                                                        ",
        "                                  T T                                                                                                                                                                   ",
        "                                                                                                                R                       A     -     A                                                   ",
        "                                                                                 T T                                                                                                                    ",
        "                                                                                                                                                                                                        ",
        "                                                                                 T T                                                                                                                    ",
        "             0                                                                                                                                                                                          ",
        "                                                                                                                                                                             |                          ",
        "                                                                                                                                        A     #     A                                                   ",
        "                                                                                                                                                                                                        ",
        "                                                      T T                                                                                                                                               ",
        "                                                                                                                                                                                                        ",
        "                                                      T T                                                                                                                                               ",
        "                       A     -     A                                                                      0                                                                                             ",
        "                                                                       R   R   R                                                        A     -     A                        |                          ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                       R   R   R         T                                                                                                              ",
        "                                                                                                                                                                                                        ",
        "                       A     #     A                                                                                                                                                                    ",
        "                                                                       R   R   R                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                     R                 R   R   R                           r                                  |                                                         ",
        "                                                                                                                                                                                                        ",
        "                       A     -     A                                                                                                                                                                    ",
        "                                                                                                                                                                 0                                      ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                         R  R  R                   0 0 0 0                                                                              ",
        "                                                 r                                                                                                                             a                        ",
        "                                                                                                                                                                                                        ",
        "                         T T T                                                                                                                                                                          ",
        "                                                               a                                                                                                                                        ",
        "                         T T T                                                                          s                                                                                               ",
        "                                                                                                                                            |                                                           ",
        "                         T T T                                                                                                                                                            0             ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                        0 0 0 0                      R  R  R                                                                            ",
        "                                                                                                                                                                                                        ",
        "                                                                         r                                                                                                                              ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                 r                   0                                  ",
        "                                                                                                                                                                                                        ",
        "                                   0                                                                     r                                                                                              ",
        "                                                                                                                                                                                                        ",
        "                                                    A      -      A                                                                                                                  R                  ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                -                                                                                       ",
        "                  R                                                                                                                                                                                     ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                  R               R                 |      #      A                                                                    0                         0 T T T  0                             ",
        "                                                                                         0                                                                                                              ",
        "                                                                                                                                                                                                        ",
        "                  R               R                                                                                                                                                                     ",
        "                                                                                                                                                                 0    #   0                             ",
        "                                                                                                     r                                                                                                  ",
        "                  R                                 A      -      |                                                                                                                                     ",
        "                                  R                                                                                                                                                                     ",
        "                                                                                                                                                                 0  T T T 0                             ",
        "                                                                                                                                                                                                        ",
        "                                  R                                                                                                                                                                     ",
        "                                                                                                                       A                                                                                ",
        "                                                                                                                                                                                                        ",
        "                                  R                                                     |                                                    0                                           R              ",
        "                                                                                                                                                                                                        ",
        "                                                     r                                                                                                                                                  ",
        "                                                                                                      T                                                                                                 ",
        "                                                                                                                                                                                                        ",
        "                        0                                                                                                                                                                               ",
        "                                                                                                                                 r                         0 0 0 0 0                                    ",
        "                                                                                                                                                                                                        ",
        "                                                                  T T                 r                                                                                                                 ",
        "                                                                                                                                                                                                        ",
        "                                                                  T T                                     -                                                                                             ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                           0 0 0 0 0                                    ",
        "                                                                                                                                                                                                        ",
        "                     T T T                                                                                             0 0 0                                                                            ",
        "                                                                                                                                                                                    r                   ",
        "                     T T T                                                          0                                                                                                                   ",
        "                                                                                                                                                                                                        ",
        "                     T T T                                                                                                                                                                              ",
        "                                                                                                                                                                                                        ",
        "                                                     |                                                                                                                                                  ",
        "                                                                                                                                                 T T                                                    ",
        "                                                                              T T T T T T T T T T T T T T T T T T                                                                                       ",
        "                                                                                                                                                 T T                                                    ",
        "                                -                                             T T T T T T T T T T T T T T T T T T                                                                                       ",
        "                                                                                                                                                                    |                |                  ",
        "                                                                              T T T T T T T         T T T T T T T                                                                                       ",
        "                                                     |                                                                                                                                                  ",
        "             |                                                                T T T T T T T    #    T T T T T T T                                                           T                           ",
        "                                                                                                                                                                                                        ",
        "                                                                              T T T T T T T         T T T T T T T                                                                                       ",
        "                                                                                                                                                                                                        ",
        "                                                                              T T T T T T T T T T T T T T T T T T                  0                                |                                   ",
        "                                                                                                                                                                                     |                  ",
        "                                   T T                                        T T T T T T T T T T T T T T T T T T                                                                                       ",
        "             |                                                                                                                                                                                          ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
    };
  }

  public double getFriction() {
    return 0.95;
  }
}
