package game.scenes;

/**
 * Level 1: Grass
 */
public class Level1 extends GameScene {

  public Level1() {
    super("grass-bg", 1);
  }

  @Override
  protected String[] getLevelLayout() {
    return new String[] {
        "                                                                              ************                                                                                                              ",
        "                                                                 t            *          *                                                                                                              ",
        "                                   t                                          *     #    *                                                                                                              ",
        "                                                                              *          *                                                     r                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                              a                                                                                         ",
        "                 0  r  0   r  0                                                                                                                                           0  0  0                       ",
        "                                               t                                                                                   0     0     0                                                        ",
        "    t                                                                                                                                                                                                   ",
        "                                                                                     r  r  r  r                                                                                                         ",
        "                                                              t                        r  r  r                                                                            0  0  0                       ",
        "                                  T       T                                          r  r  r  r                                    0     0     0                                                        ",
        "                                      0                                                                                                                                                                 ",
        "                                  T       T                                                                                                                                                             ",
        "               t                                                                                                                                                                                        ",
        "                                  T   #   T                                                                                                                                                             ",
        "                                                        -     -     -                                                                                                                                   ",
        "                                                                                                                                                                                                        ",
        "                      r  r  r                                                                                  R   R    r    R   R                                                                      ",
        "     t                                                        r                                                                                      **                                                 ",
        "                                                                                                                                                     **                                                 ",
        "                      r  r  r                                                                                  R   R    0    R   R                                                                      ",
        "     t                               *                  -     a     -                                                                                                                                   ",
        "                                                                                                                                                                                                        ",
        "                      r  r  r                                                                                  R   R    r    R   R                                T T T                                 ",
        "     t                                                                                                                                                                                                  ",
        "                                                                                                                                                                  T T T                                 ",
        "                                                                                                                                                                                                        ",
        "                                                                                          T T T T                                                                 T T T                                 ",
        "                                                                                                                                                                                                        ",
        "                                             *                                                                                                                                                          ",
        "              T  T                                                                        T T T T                    0  0  0  0                                                                         ",
        "                                                                                                                                                                                                        ",
        "              T  T                                                                                                                                                                                      ",
        "                                                                          t                                                                                                                             ",
        "                                                                                                                                                                                                        ",
        "                   -                                                                                                                                                                    t               ",
        "                                               T T                                                                                                                                                      ",
        "                                                                                                                                               t t t t t t                                              ",
        "                                               T T                                                                                                                                                      ",
        "              |    #   |                                                                                       T T                                                                                      ",
        "                                                                                                                                                                                                        ",
        "                                                                                                               T T                             t t t t t t                      A                       ",
        "                                                                                            *                                                                                                           ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "              |        |                                                                                                                                                                                ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                      -     -     -      -                                                                           TTTTTTTTTTTTTTTT                   ",
        "                                                                                                                                                                                                        ",
        "              |        |                          t                                                                                               |                  TTTTTTTTTTTTTTTT                   ",
        "                                                                                                                           t                                                                            ",
        "                  0                                                                                                                                                  TTTTTTTTTTTTTTTT                   ",
        "                                                                                                                                                                                           *            ",
        "                                                                                                                                                                                                        ",
        "                                                                                             0                                                                                                          ",
        "              |        |                                      TTTTTTTTTTTTTTT                                                                     |                                                     ",
        "                                                                                                                                                                                                        ",
        "                                                              TTTTTTTTTTTTTTT                                                  0                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                              TTTT       TTTT                                                                                                                           ",
        "                                                                                                                                                                                                        ",
        "                            |       |                         TTTT   #   TTTT                             t                                                                                             ",
        "                                                                                                                                                                                                        ",
        "                                                              TTTT       TTTT                                                                     |                                                     ",
        "                                                                                                                                                                                                        ",
        "                                                              TTTTTTTTTTTTTTT                                                                                                                           ",
        "                                                                                                                                                                                                        ",
        "                            |   0   |                         TTTTTTTTTTTTTTT                                    R                                                                        *             ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                              0    0                                    ",
        "                                                                                                    s                                        r                                                          ",
        "                                                                                                                                                                                                        ",
        "                            |       |                                       C                                                                                                                           ",
        "                                                                                                                                                                                                        ",
        "                                                                                          0                      R                                                                                      ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                           A                |                           ",
        "                                                                                                                                                                                                        ",
        "                                    A                                                                                                                                                        t          ",
        "                                                                                                                                                                                                        ",
        "                                                                                                    t                                                              0                                    ",
        "                                                                        -          -                           t                                                                                        ",
        "                                                                                                                                  0                                                                     ",
        "                                                    t                                                                                                                                                   ",
        "            T T T T                                                                                                                                       |                 |                           ",
        "                                                                                                                                                                                                        ",
        "            T T T T                                                                                                                                                                                     ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                        r  r  r                                                                                         ",
        "                                                                               -                                                                                                                        ",
        "                                     T T                                                                r  r  r                                           |                 A                           ",
        "                                                                                                                                          t                                                             ",
        "                                     T T                                                                                                                                                                ",
        "                                                               t                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                               r        ",
        "                                                                                                                                                                                                        ",
        "          ********                                                                             t                                                                                                        ",
        "        ************                                                                                                                                                                                    ",
        "        ************                                                                                                                                                                                    ",
        "          ********                                                                                                                                                      R                               ",
        "                                         t                                            t                                   t                T T T T T T T T                                              ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                   0                    ",
        "          T T T T T                                                           *              0 0                                                                                                        ",
        "                                                                                                                                                                                                        ",
        "          T T T T T                                 0                                                                                                                                                   ",
        "                                                                                                                T T                                  T T T T T T T T T                                  ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                T T                                                                                     ",
        "                                        |                                                                                                                                                               ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                               t        ",
        "                                                               ***********                                                                                                                              ",
        "                          t                                   **************                                                                                                                            ",
        "                                                                **********                                                                                                                              ",
        "                                                                                                                                                r  r  r  r  r  r  r  r  r  r  r  r  r                   ",
        "                                        |                                                                     t                                                                                         ",
        "                                                                                a                                                                                                   R                   ",
        "                                                                                                                                                                                                        ",
        "           0                                                                                *                                                     T  T  T   T    T     a                                ",
        "                                                                                                                                                                                    R                   ",
        "                                                                                                                     t                                                                                  ",
        "                                                                                                                                    R                                                                   ",
        "                                             0                                                                                                                                      R                   ",
        "                                                                                                                                                              #                                         ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                  T   T     T        T     a        R                   ",
        "               t  t  t                                 t  t  t                      R            R                                                                                                      ",
        "                                                                                                                                                                                                        ",
        "                             *               *                                                                                                   r  r  r  r  r  r  r  r  r  r  r   r                    ",
        "                                                                                    R            R                                                                                                      ",
        "                                                                                                                                                                                                        ",
        "                                     #                                                                                                                                                                  ",
        "                                                                                    R            R                                                                                                      ",
        "                                                                                                                        0 0 0 0 0                                        |                              ",
        "                             *               *                                                                                                                                                          ",
        "               t  t  t                                  t  t  t                                                                                                                                         ",
        "                                                                                                                                                                                                        ",
        "                                                                                                                                                                                                        ",
    };
  }

  public double getFriction() {
    return 0.95;
  }
}
